### ISSUE TITLE
Question to the instructors on the project

### ISSUE THREAD

**Issue by hveravallaskreppur** [nipraxis-summer-2023/diagnostics-bold_but_better#27]
Hi @matthew-brett,
our project is currently rather basic. It runs but only prints out outliers in each scan according to x nr of std from the mean. We intend to prove it using other outlier detection methods (like IQR) and provide a guesstimate on why we think it is better.

A few questions on the project:
i) our understanding is that the project is focused our pre-processing of fMRI data. Meaning that if an fMRI project were split into three phases: 1) data collection (scans), 2) pre-processing and 3) statistical analysis (HRF etc.), this project is purely focused on the middle part, i.e. pre-processing – therefore we shouldn't be applying SPM or GLM or anything to the scans, right?
ii) we didn't have time to dive deep into transformations in the course (last lecture) are you expecting us to to do any movement corrections before applying outlier detections?
iii) any hints or guidance on what is a "pass" and what is a "well done" in terms of project delivery would be much appreciated :)

**Comment by hveravallaskreppur** [comment]
Hi @matthew-brett, I sent the above question on Wednesday, did you see it? Adding @oesteban @effigies

I don't think we'll be able to deliver the project today.

**Comment by matthew-brett** [comment]
Sorry for the delay - I'm just getting ready to start my teaching this term, and it's been busy.

> A few questions on the project:
> i) our understanding is that the project is focused our pre-processing of fMRI data. Meaning that if an fMRI project were split into three phases: 1) data collection (scans), 2) pre-processing and 3) statistical analysis (HRF etc.), this project is purely focused on the middle part, i.e. pre-processing – therefore we shouldn't be applying SPM or GLM or anything to the scans, right?

That's your call - I said something about this in the sessions - but you can do any level, from just considering the scans as they are, without further processing, all the way through to testing your techniques on the error data from the statistical model - that is, seeing whether the scan is an outlier, taking the statistical model into account.

> ii) we didn't have time to dive deep into transformations in the course (last lecture) are you expecting us to to do any movement corrections before applying outlier detections?

We didn't get into that, so no, I'm not expecting you to do that - of course, you might consider doing that, if you know how to using other tools, such as SPM or FSL, and you have time to investigate.

> iii) any hints or guidance on what is a "pass" and what is a "well done" in terms of project delivery would be much appreciated :)

Pass is spending some time thinking about how to calculate measure to detect outliers, and some evidence that you've investigated different methods and evaluated them for performance on some metric you think is sensible - even if this is reproducing what looks to you - by eye - to be outliers.

Well done is going deeper into the problem, perhaps by considering pre-processing, perhaps by taking the statisical model into account, perhaps by comparing to other off-the-shelf methods - and comparing performance in a more formal way between methods - your methods, or other methods.

**Comment by hveravallaskreppur** [comment]
That's very helpful, thank you
well plough on,
Best
David
________________________________

**Comment by hveravallaskreppur** [comment]
@matthew-brett 
I am struggling to understand the events files with the scans. The TR is clearly not 2.5 is in the course examples. Looking at the events file for subject 1:

onset	duration	trial_type	0	1	2	3
0.000	0.350	Words	mist	1	NR	NR
1.000	0.350	Words	otter	1	NR	NR
2.000	0.350	Words	otter	1	34	577
3.000	0.350	Words	verse	1	NR	NR
4.000	0.350	Words	pail	1	NR	NR
...

I'm trying to work out a convolved time course just looking at the first two columns, onset and duration. But how could this be? Is the TR =0.5sec or something and the participant bombarded with stimulus (events) every second??

**Comment by effigies** [comment]
@hveravallaskreppur The task stimulus can be presented at a different rate than the scanner is recording. Generally, you will need to construct a stimulus time course at a fairly high temporal resolution (perhaps 0.01s), convolve it with an HRF, and then downsample the convolved timecourse to the sampling rate of the BOLD image.

**Comment by matthew-brett** [comment]
Following on from Chris' response - the stimuli were words presented every second.   You can actually find the correct TR in the Nibabel header data (`pixdim[4]`) - it's 3 seconds.   You might want to look at https://textbook.nipraxis.org/non_tr_onsets.html

**Comment by hveravallaskreppur** [comment]
Thanks for a quick reply, @effigies, @matthew-brett . I think I understand, will make some attempts. Trying to use GLM as the the outlier method metric and compare F statistic before and after removing outliers, per method. Hope that makes sense

**Comment by hveravallaskreppur** [comment]
@matthew-brett  can I assume that the fourth column in the .tsv is the amplitude? I can see that some rows have "NR" (not recorded?) ?

**Comment by matthew-brett** [comment]
The columns in the file have names:

```
onset   duration        trial_type      0       1       2       3
```

I happen to know that the "trial_type" column is wrong, you should ignore it.   Column 1 gives the trial type where 1 = Words, 2 = Consonant strings, 3 = objects, and 4 = scrambled objects.  Column 0 gives the name of the stimulus presented.  Column 2 gives the button pressed or NR if no button pressed (they always seem to press button 34).   Column 3 gives the reaction time in milliseconds or NR if no button pressed.

Column 1 is the stimulus string presented.

**Comment by hveravallaskreppur** [comment]
answers provided with thanks
